# OpenManus MySQL配置示例
# 复制此文件为 config.toml 并修改相应配置

# =============================================================================
# LLM配置 (必需)
# =============================================================================
[llm]
model = "claude-3-5-sonnet-20241022"
base_url = "https://api.anthropic.com"
api_key = "your-anthropic-api-key"
max_tokens = 4096
temperature = 1.0
api_type = "anthropic"
api_version = ""

# =============================================================================
# MySQL数据库配置 (可选，如果不配置则使用环境变量)
# =============================================================================
[mysql]
# 数据库服务器地址
host = "127.0.0.1"

# 数据库端口
port = 3306

# 数据库用户名 (必填)
user = "your_mysql_username"

# 数据库密码 (必填)
password = "your_mysql_password"

# 数据库名称 (必填)
database = "your_database_name"

# 字符集 (默认: utf8mb4)
charset = "utf8mb4"

# 连接超时时间，单位：秒 (默认: 30)
connect_timeout = 30

# 读取超时时间，单位：秒 (默认: 30)
read_timeout = 30

# 写入超时时间，单位：秒 (默认: 30)
write_timeout = 30

# =============================================================================
# 沙盒配置 (可选)
# =============================================================================
[sandbox]
use_sandbox = false
image = "python:3.12-slim"
work_dir = "/workspace"
memory_limit = "512m"
cpu_limit = 1.0
timeout = 300
network_enabled = false

# =============================================================================
# 运行流程配置 (可选)
# =============================================================================
[runflow]
use_data_analysis_agent = true

# =============================================================================
# MCP配置 (可选)
# =============================================================================
[mcp]
server_reference = "app.mcp.server"

# =============================================================================
# 使用说明:
# =============================================================================
# 1. 复制此文件为 config/config.toml
# 2. 修改 [mysql] 部分的连接信息
# 3. 修改 [llm] 部分的API配置
# 4. 运行程序: python examples/mysql_usage_guide.py
#
# 配置优先级:
# 1. 配置文件中的 [mysql] 部分
# 2. 环境变量 (MYSQL_HOST, MYSQL_PORT, MYSQL_USER, MYSQL_PASSWORD, MYSQL_DATABASE)
#
# 注意事项:
# - user, password, database 是必填字段
# - 其他字段都有默认值，可以不填写
# - 如果不配置 [mysql] 部分，将使用环境变量
